CREATE TABLE DEPARTMENTS(DEPARTMENT_ID NUMBER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
LOCATION VARCHAR2(100)
);


CREATE TABLE PATIENTS(PATIENT_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50)NOT NULL,
BIRTH_DATE DATE,
GENDER CHAR(2),
AGE NUMBER,
PHONE_NUMBER VARCHAR2(25) NOT NULL,
ADDRESS VARCHAR2(200),
EMAIL VARCHAR2(100)
);


CREATE TABLE DOCTORS(DOCTOR_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
SPECIALTY VARCHAR2(50),
SALARY NUMBER,
EMAIL VARCHAR2(100) DEFAULT'abcabc@outlook.com',
PHONE_NUMBER VARCHAR2(15),
DEPARTMENT_ID NUMBER,
PATIENT_ID NUMBER,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);


CREATE TABLE ROOMS( ROOM_ID NUMBER PRIMARY KEY,
ROOM_NUMBER CHAR(4) NOT NULL,
PATIENT_ID NUMBER,
ROOM_TYPE VARCHAR2(20),
AVAILABLE VARCHAR2(5), 
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);


CREATE TABLE APPOINTMENTS(APPOINTMENT_ID NUMBER PRIMARY KEY,
PATIENT_ID NUMBER,
DOCTOR_ID NUMBER,
APOINTMENT_DATE DATE,
TIME VARCHAR2(10),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS (DOCTOR_ID)
);


CREATE TABLE BILLS(BILL_ID NUMBER PRIMARY KEY,
PATIENT_ID NUMBER,
AMOUNT NUMBER(10, 2),
BILL_DATE DATE,
PAYMENT_STATUS VARCHAR2(20),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);
